{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = VERSION %}
{% set project = pyproject['project'] %}

package:
  name: tradestation-python
  version: {{ version }}

source:
  path: ../..
  
build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION
  entry_points:
    {% for name, reference in project['scripts'].items() %}
    - {{ name }} = {{ reference }}
    {% endfor %}

requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # build:
  #   - {{ compilers('c') }}
  host:
    - python {{ project['requires-python'] }}
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python {{ project['requires-python'] }}
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - tradestation_python
  source_files:
    - tradestation-python/tests
  requires:
    {% for dep in project['optional-dependencies']['test'] %}
    - {{ dep.lower() }}
    {% endfor %}
  commands:
    - pytest tradestation-python/tests
    {% for name in project['scripts'] %}
    - {{ name }}
    {% endfor %}
    - python -c "from tradestation_python import __version__; assert __version__ == \"{{ version }}\""

about:
  home: https://github.com/jkim-mlops/tradestation-python
  summary: TradeStation Python Client SDK.
  license: {{ pyproject.get('license') }}
  license_file: tradestation-python/LICENSE
